application: beeline-invoice-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_email.py
  login: admin

- url: /css
  static_dir: static/css

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

- url: /img
  static_dir: static/img

- url: /img/(.*)
  static_files: static/img/\1
  upload: static/img/(.*)

- url: /js
  static_dir: static/js

- url: /js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)

- url: .*
  script: main.app
  login: admin

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
