application: beeline-invoice
version: 1
runtime: python
api_version: 1

builtins:
- deferred: on

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_email.py
  login: admin

- url: /css
  static_dir: static/css

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

- url: .*
  script: main.py
  login: admin
